version: 0.0
os: linux 

files:
  - source: scripts
    destination: /home/ubuntu/test_app/scripts
  - source: .mvn
    destination: /home/ubuntu/test_app/.mvn
  - source: src
    destination: /home/ubuntu/test_app/src
  - source: mvnw
    destination: /home/ubuntu/test_app/mvnw
  - source: pom.xml
    destination: /home/ubuntu/test_app/pom.xml

hooks:

  ApplicationStop:
    - location: /home/ubuntu/test_app/scripts/stop
      timeout: 30
      runas: ubuntu

  BeforeInstall:
    - location: /home/ubuntu/test_app/scripts/copy_config
      timeout: 10
      runas: ubuntu

  ApplicationStart:
    - location: /home/ubuntu/test_app/scripts/start
      timeout: 30
      runas: ubuntu

  ValidateService:
    - location: /home/ubuntu/test_app/scripts/validate
      timeout: 200
      runas: ubuntu
