#!/bin/bash
cd $HOME/test_app

if ! pgrep -F app.pid > /dev/null 2>&1
then
    echo "App is not running"
    exit 1
fi

timeout=180

until [ $timeout -eq 0 ]
do
    if fgrep "Started SuchappApplication" app.log
    then
        break
    else
        sleep 10
        let timeout-=10
    fi
done

if [ $timeout -eq 0 ]
then
    echo "After 3 minutes App didn't start!"
    exit 1
fi
